apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gold-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: gold-platform
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

